version: "3.8"
services:
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ~/data/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
